version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  producer:
    build:
      context: .
      dockerfile: ./compose/local/producer/Dockerfile
    image: kafka_producer
    container_name: producer
    depends_on:
      - zookeeper
      - broker
    volumes:
      - ./data:/producer/src/data

  logic_consumer:
    build:
      context: .
      dockerfile: ./compose/local/consumer/logic/Dockerfile
    image: kafka_logic_consumer
    container_name: logic_consumer
    depends_on:
      - zookeeper
      - broker

  result_consumer:
    build:
      context: .
      dockerfile: ./compose/local/consumer/result/Dockerfile
    image: kafka_result_consumer
    container_name: result_consumer
    depends_on:
      - zookeeper
      - broker
    